Module 16
DaniyarKulmanov/railway_station pull request #2
Opened 2017-10-16 11:02 UTC by DaniyarKulmanov

2017-10-16 13:23 UTC, vkurennov requested changes

2017-10-16 13:23 UTC, vkurennov commented on app/controllers/trains_controller.rb
> +      params.require(:train).permit(:number, :current_station_id, :route_id, :sort_asc, :sort_dsc)
Не стоит 2 параметра под это отводить. Это же флаг, т.е. либо одно значение, либо другое. А для флага достаточно одного атрибута типа boolean

2017-10-16 13:23 UTC, vkurennov commented on app/models/route.rb
> +    errors.add(:name, 'Name error :D !')
В таком случае, у тебя будет всегда маршрут невалидным, ты же без условия просто ошибку добавляешь

2017-10-16 13:23 UTC, vkurennov commented on app/models/train.rb
>       self.wagons.each do |wagon|
Так, а теперь вспомниаем содержимое скринкаста и все эти where, sum и прочие методы, и думаем, как же их применить тут, чтобы все считать через базу :-)

2017-10-16 13:23 UTC, vkurennov commented on app/models/wagon.rb
> +    self.comfort_level = 'Купе' if self.instance_of? CoupeWagon
А зачем дублировать снова эту информацию? Достаточно ведб тип хранить, а по нему получать "человеческое" название.

2017-10-16 13:23 UTC, vkurennov commented on app/models/wagon.rb
> +     self.position = self.train.wagons.size + 1 if self.train
Ситуация: было 5 вагонов с номерами от 1 до 5. Удалили вагон 3, остались вагоны с номерами 1,2,4,5, но всего их 4. Добавляем новый вагон. В твоем коде, ему будет присвоен номер 5, у поезда получится два 5-х вагона, чего как раз нам и нужно избежать.

2017-10-16 13:23 UTC, vkurennov commented on app/views/trains/_form.html.erb
> +    <%= form.radio_button :sort, :sort_asc, checked: true %>
если заменить на один boolean-атрибут, то тут отлично подойдет чекбокс.

2017-10-16 13:23 UTC, vkurennov commented on app/views/trains/show.html.erb
> +      <% if @train.sort_dsc = true %>
Не надо сравнивать с true логические атрибуты. У тебя и так атрибут вернет true или false, зачем еще сравнивать? Если вернет true, условие выполнится, если false - не выполнится.

2017-10-19 17:34 UTC, iBublik requested changes

2017-10-19 17:34 UTC, iBublik commented on app/controllers/trains_controller.rb
> +      params.require(:train).permit(:number, :current_station_id, :route_id, :sort_asc, :sort_dsc)
Замечание актуально

2017-10-19 17:34 UTC, iBublik commented on app/models/railway_station.rb
> +  # scope :sorted, -> {
Ненужные комментарии надо подчищать

2017-10-19 17:34 UTC, iBublik commented on app/models/railway_stations_route.rb
> +  default_scope { order(:station_number) }
Крайне не рекомендую использовать `default_scope` - от него очень сложно избавиться потом, и все время надо о нем помнить.

2017-10-19 17:34 UTC, iBublik commented on app/models/train.rb
> +    self.wagons.count { |wagon| wagon.type == type }
Неэффективно такие подсчеты делать на Ruby, БД то же самое сделает в разы быстрее

2017-10-19 17:34 UTC, iBublik commented on app/models/train.rb
> +     self.wagons.where(type: type).sum(seat)
`self` тут избыточен

2017-10-19 17:34 UTC, iBublik commented on app/models/wagon.rb
> +  def name
У нас же есть отдельные классы вагонов, там можно без всяких `case`-ов вернуть имя для отображения. Плюс родительский класс не должен что-то знать о своих наследниках

2017-10-19 17:34 UTC, iBublik commented on app/models/wagon.rb
> +    if self.train && self.train.wagons.last
Зачем делать эти проверки, если можно просто взять максимальное значение позиции, привести его к числу (если еще не создано вагонов) и прибавить единицу? Метод намного проще и короче станет

2017-10-19 17:34 UTC, iBublik commented on db/migrate/20171016100234_add_boolean_to_trains.rb
> +    add_column :trains, :sort_asc, :boolean
Задай дефолтное значение и сделай `null: false`, чтоб поле было истинно логическим (сейчас оно может 3 состояния содержать)

2017-10-19 17:34 UTC, iBublik commented on app/models/wagon.rb
> +  WAGON_TYPE = [ 'CoupeWagon', 'EconomWagon', 'CbWagon', 'SittingWagon' ].freeze
Не увидел где эта константа используется

2017-10-19 17:34 UTC, iBublik commented on app/views/trains/show.html.erb
> +      <% if @train.sort_asc %>
Вся логика сортировки должны быть инкапсулирована в модели. Т.е. тут ты пишешь `trains.sorted_wagons.each ...` без всяких проверок

2017-10-19 17:34 UTC, iBublik commented on app/views/trains/show.html.erb
> +        <% @train.wagons.reverse_each do |wagon| %>
Сортировкой должен не Ruby заниматься, а БД

2017-10-19 17:34 UTC, iBublik commented on app/views/wagons/show.html.erb
> +<%if !@wagon.upper_seats.nil?%>
Очень много логики во вьюхах - сложно понять что тут происходит. Лучше выдели под каждый тип вагона отдельный партиал, и рендери его на основании поля `type`

2017-10-21 10:48 UTC, vkurennov approved these changes

2017-10-21 10:48 UTC, vkurennov commented on app/controllers/wagons_controller.rb
> +    @wagon.type = wagon_params[:type]
Зачем явно устанавливать тип, он и так у тебя в wagon_params передается и строкой выше устанаваливается

2017-10-23 15:16 UTC, merged